// <auto-generated />
using System;
using FribergFastigheterApi.Data.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FribergFastigheterApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240414180848_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FribergFastigheter.Data.Entities.Housing", b =>
                {
                    b.Property<int>("HousingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HousingId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AncillaryArea")
                        .HasColumnType("float");

                    b.Property<int>("BrokerFirmId")
                        .HasColumnType("int");

                    b.Property<int>("BrokerId")
                        .HasColumnType("int");

                    b.Property<int?>("BuildYear")
                        .HasColumnType("int");

                    b.Property<int>("CategoryHousingCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LandArea")
                        .HasColumnType("float");

                    b.Property<double>("LivingArea")
                        .HasColumnType("float");

                    b.Property<decimal?>("MonthlyFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("RoomCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("YearlyRunningCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("HousingId");

                    b.HasIndex("BrokerFirmId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("CategoryHousingCategoryId");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Housings");
                });

            modelBuilder.Entity("FribergFastigheterApi.Data.Entities.Broker", b =>
                {
                    b.Property<int>("BrokerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrokerId"));

                    b.Property<int>("BrokerFirmId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrokerId");

                    b.HasIndex("BrokerFirmId");

                    b.ToTable("Brokers");
                });

            modelBuilder.Entity("FribergFastigheterApi.Data.Entities.BrokerFirm", b =>
                {
                    b.Property<int>("BrokerFirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrokerFirmId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrokerFirmId");

                    b.ToTable("BrokerFirms");
                });

            modelBuilder.Entity("FribergFastigheterApi.Data.Entities.HousingCategory", b =>
                {
                    b.Property<int>("HousingCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HousingCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HousingCategoryId");

                    b.ToTable("HousingCategories");

                    b.HasData(
                        new
                        {
                            HousingCategoryId = 1,
                            CategoryName = "Bostadsrättslägenhet"
                        },
                        new
                        {
                            HousingCategoryId = 2,
                            CategoryName = "Bostadsrättsradhus"
                        },
                        new
                        {
                            HousingCategoryId = 3,
                            CategoryName = "Fritidshus"
                        },
                        new
                        {
                            HousingCategoryId = 4,
                            CategoryName = "Villa"
                        });
                });

            modelBuilder.Entity("FribergFastigheterApi.Data.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HousingId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("HousingId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("FribergFastigheterApi.Data.Entities.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipalityId"));

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MunicipalityId");

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            MunicipalityId = 1,
                            MunicipalityName = "Ale kommun"
                        },
                        new
                        {
                            MunicipalityId = 2,
                            MunicipalityName = "Alingsås kommun"
                        },
                        new
                        {
                            MunicipalityId = 3,
                            MunicipalityName = "Alvesta kommun"
                        },
                        new
                        {
                            MunicipalityId = 4,
                            MunicipalityName = "Aneby kommun"
                        },
                        new
                        {
                            MunicipalityId = 5,
                            MunicipalityName = "Arboga kommun"
                        },
                        new
                        {
                            MunicipalityId = 6,
                            MunicipalityName = "Arjeplogs kommun"
                        },
                        new
                        {
                            MunicipalityId = 7,
                            MunicipalityName = "Arvidsjaurs kommun"
                        },
                        new
                        {
                            MunicipalityId = 8,
                            MunicipalityName = "Arvika kommun"
                        },
                        new
                        {
                            MunicipalityId = 9,
                            MunicipalityName = "Askersunds kommun"
                        },
                        new
                        {
                            MunicipalityId = 10,
                            MunicipalityName = "Avesta kommun"
                        },
                        new
                        {
                            MunicipalityId = 11,
                            MunicipalityName = "Bengtsfors kommun"
                        },
                        new
                        {
                            MunicipalityId = 12,
                            MunicipalityName = "Bergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 13,
                            MunicipalityName = "Bjurholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 14,
                            MunicipalityName = "Bjuvs kommun"
                        },
                        new
                        {
                            MunicipalityId = 15,
                            MunicipalityName = "Bodens kommun"
                        },
                        new
                        {
                            MunicipalityId = 16,
                            MunicipalityName = "Bollebygds kommun"
                        },
                        new
                        {
                            MunicipalityId = 17,
                            MunicipalityName = "Bollnäs kommun"
                        },
                        new
                        {
                            MunicipalityId = 18,
                            MunicipalityName = "Borgholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 19,
                            MunicipalityName = "Borlänge kommun"
                        },
                        new
                        {
                            MunicipalityId = 20,
                            MunicipalityName = "Borås kommun"
                        },
                        new
                        {
                            MunicipalityId = 21,
                            MunicipalityName = "Botkyrka kommun"
                        },
                        new
                        {
                            MunicipalityId = 22,
                            MunicipalityName = "Boxholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 23,
                            MunicipalityName = "Bromölla kommun"
                        },
                        new
                        {
                            MunicipalityId = 24,
                            MunicipalityName = "Bräcke kommun"
                        },
                        new
                        {
                            MunicipalityId = 25,
                            MunicipalityName = "Burlövs kommun"
                        },
                        new
                        {
                            MunicipalityId = 26,
                            MunicipalityName = "Båstads kommun"
                        },
                        new
                        {
                            MunicipalityId = 27,
                            MunicipalityName = "Dals-Eds kommun"
                        },
                        new
                        {
                            MunicipalityId = 28,
                            MunicipalityName = "Danderyds kommun"
                        },
                        new
                        {
                            MunicipalityId = 29,
                            MunicipalityName = "Degerfors kommun"
                        },
                        new
                        {
                            MunicipalityId = 30,
                            MunicipalityName = "Dorotea kommun"
                        },
                        new
                        {
                            MunicipalityId = 31,
                            MunicipalityName = "Eda kommun"
                        },
                        new
                        {
                            MunicipalityId = 32,
                            MunicipalityName = "Ekerö kommun"
                        },
                        new
                        {
                            MunicipalityId = 33,
                            MunicipalityName = "Eksjö kommun"
                        },
                        new
                        {
                            MunicipalityId = 34,
                            MunicipalityName = "Emmaboda kommun"
                        },
                        new
                        {
                            MunicipalityId = 35,
                            MunicipalityName = "Enköpings kommun"
                        },
                        new
                        {
                            MunicipalityId = 36,
                            MunicipalityName = "Eskilstuna kommun"
                        },
                        new
                        {
                            MunicipalityId = 37,
                            MunicipalityName = "Eslövs kommun"
                        },
                        new
                        {
                            MunicipalityId = 38,
                            MunicipalityName = "Essunga kommun"
                        },
                        new
                        {
                            MunicipalityId = 39,
                            MunicipalityName = "Fagersta kommun"
                        },
                        new
                        {
                            MunicipalityId = 40,
                            MunicipalityName = "Falkenbergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 41,
                            MunicipalityName = "Falköpings kommun"
                        },
                        new
                        {
                            MunicipalityId = 42,
                            MunicipalityName = "Falu kommun"
                        },
                        new
                        {
                            MunicipalityId = 43,
                            MunicipalityName = "Filipstads kommun"
                        },
                        new
                        {
                            MunicipalityId = 44,
                            MunicipalityName = "Finspångs kommun"
                        },
                        new
                        {
                            MunicipalityId = 45,
                            MunicipalityName = "Flens kommun"
                        },
                        new
                        {
                            MunicipalityId = 46,
                            MunicipalityName = "Forshaga kommun"
                        },
                        new
                        {
                            MunicipalityId = 47,
                            MunicipalityName = "Färgelanda kommun"
                        },
                        new
                        {
                            MunicipalityId = 48,
                            MunicipalityName = "Gagnefs kommun"
                        },
                        new
                        {
                            MunicipalityId = 49,
                            MunicipalityName = "Gislaveds kommun"
                        },
                        new
                        {
                            MunicipalityId = 50,
                            MunicipalityName = "Gnesta kommun"
                        },
                        new
                        {
                            MunicipalityId = 51,
                            MunicipalityName = "Gnosjö kommun"
                        },
                        new
                        {
                            MunicipalityId = 52,
                            MunicipalityName = "Region Gotland"
                        },
                        new
                        {
                            MunicipalityId = 53,
                            MunicipalityName = "Grums kommun"
                        },
                        new
                        {
                            MunicipalityId = 54,
                            MunicipalityName = "Grästorps kommun"
                        },
                        new
                        {
                            MunicipalityId = 55,
                            MunicipalityName = "Gullspångs kommun"
                        },
                        new
                        {
                            MunicipalityId = 56,
                            MunicipalityName = "Gällivare kommun"
                        },
                        new
                        {
                            MunicipalityId = 57,
                            MunicipalityName = "Gävle kommun"
                        },
                        new
                        {
                            MunicipalityId = 58,
                            MunicipalityName = "Göteborgs kommun"
                        },
                        new
                        {
                            MunicipalityId = 59,
                            MunicipalityName = "Götene kommun"
                        },
                        new
                        {
                            MunicipalityId = 60,
                            MunicipalityName = "Habo kommun"
                        },
                        new
                        {
                            MunicipalityId = 61,
                            MunicipalityName = "Hagfors kommun"
                        },
                        new
                        {
                            MunicipalityId = 62,
                            MunicipalityName = "Hallsbergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 63,
                            MunicipalityName = "Hallstahammars kommun"
                        },
                        new
                        {
                            MunicipalityId = 64,
                            MunicipalityName = "Halmstads kommun"
                        },
                        new
                        {
                            MunicipalityId = 65,
                            MunicipalityName = "Hammarö kommun"
                        },
                        new
                        {
                            MunicipalityId = 66,
                            MunicipalityName = "Haninge kommun"
                        },
                        new
                        {
                            MunicipalityId = 67,
                            MunicipalityName = "Haparanda kommun"
                        },
                        new
                        {
                            MunicipalityId = 68,
                            MunicipalityName = "Heby kommun"
                        },
                        new
                        {
                            MunicipalityId = 69,
                            MunicipalityName = "Hedemora kommun"
                        },
                        new
                        {
                            MunicipalityId = 70,
                            MunicipalityName = "Helsingborgs kommun"
                        },
                        new
                        {
                            MunicipalityId = 71,
                            MunicipalityName = "Herrljunga kommun"
                        },
                        new
                        {
                            MunicipalityId = 72,
                            MunicipalityName = "Hjo kommun"
                        },
                        new
                        {
                            MunicipalityId = 73,
                            MunicipalityName = "Hofors kommun"
                        },
                        new
                        {
                            MunicipalityId = 74,
                            MunicipalityName = "Huddinge kommun"
                        },
                        new
                        {
                            MunicipalityId = 75,
                            MunicipalityName = "Hudiksvalls kommun"
                        },
                        new
                        {
                            MunicipalityId = 76,
                            MunicipalityName = "Hultsfreds kommun"
                        },
                        new
                        {
                            MunicipalityId = 77,
                            MunicipalityName = "Hylte kommun"
                        },
                        new
                        {
                            MunicipalityId = 78,
                            MunicipalityName = "Håbo kommun"
                        },
                        new
                        {
                            MunicipalityId = 79,
                            MunicipalityName = "Hällefors kommun"
                        },
                        new
                        {
                            MunicipalityId = 80,
                            MunicipalityName = "Härjedalens kommun"
                        },
                        new
                        {
                            MunicipalityId = 81,
                            MunicipalityName = "Härnösands kommun"
                        },
                        new
                        {
                            MunicipalityId = 82,
                            MunicipalityName = "Härryda kommun"
                        },
                        new
                        {
                            MunicipalityId = 83,
                            MunicipalityName = "Hässleholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 84,
                            MunicipalityName = "Höganäs kommun"
                        },
                        new
                        {
                            MunicipalityId = 85,
                            MunicipalityName = "Högsby kommun"
                        },
                        new
                        {
                            MunicipalityId = 86,
                            MunicipalityName = "Hörby kommun"
                        },
                        new
                        {
                            MunicipalityId = 87,
                            MunicipalityName = "Höörs kommun"
                        },
                        new
                        {
                            MunicipalityId = 88,
                            MunicipalityName = "Jokkmokks kommun"
                        },
                        new
                        {
                            MunicipalityId = 89,
                            MunicipalityName = "Järfälla kommun"
                        },
                        new
                        {
                            MunicipalityId = 90,
                            MunicipalityName = "Jönköpings kommun"
                        },
                        new
                        {
                            MunicipalityId = 91,
                            MunicipalityName = "Kalix kommun"
                        },
                        new
                        {
                            MunicipalityId = 92,
                            MunicipalityName = "Kalmar kommun"
                        },
                        new
                        {
                            MunicipalityId = 93,
                            MunicipalityName = "Karlsborgs kommun"
                        },
                        new
                        {
                            MunicipalityId = 94,
                            MunicipalityName = "Karlshamns kommun"
                        },
                        new
                        {
                            MunicipalityId = 95,
                            MunicipalityName = "Karlskoga kommun"
                        },
                        new
                        {
                            MunicipalityId = 96,
                            MunicipalityName = "Karlskrona kommun"
                        },
                        new
                        {
                            MunicipalityId = 97,
                            MunicipalityName = "Karlstads kommun"
                        },
                        new
                        {
                            MunicipalityId = 98,
                            MunicipalityName = "Katrineholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 99,
                            MunicipalityName = "Kils kommun"
                        },
                        new
                        {
                            MunicipalityId = 100,
                            MunicipalityName = "Kinda kommun"
                        },
                        new
                        {
                            MunicipalityId = 101,
                            MunicipalityName = "Kiruna kommun"
                        },
                        new
                        {
                            MunicipalityId = 102,
                            MunicipalityName = "Klippans kommun"
                        },
                        new
                        {
                            MunicipalityId = 103,
                            MunicipalityName = "Knivsta kommun"
                        },
                        new
                        {
                            MunicipalityId = 104,
                            MunicipalityName = "Kramfors kommun"
                        },
                        new
                        {
                            MunicipalityId = 105,
                            MunicipalityName = "Kristianstads kommun"
                        },
                        new
                        {
                            MunicipalityId = 106,
                            MunicipalityName = "Kristinehamns kommun"
                        },
                        new
                        {
                            MunicipalityId = 107,
                            MunicipalityName = "Krokoms kommun"
                        },
                        new
                        {
                            MunicipalityId = 108,
                            MunicipalityName = "Kumla kommun"
                        },
                        new
                        {
                            MunicipalityId = 109,
                            MunicipalityName = "Kungsbacka kommun"
                        },
                        new
                        {
                            MunicipalityId = 110,
                            MunicipalityName = "Kungsörs kommun"
                        },
                        new
                        {
                            MunicipalityId = 111,
                            MunicipalityName = "Kungälvs kommun"
                        },
                        new
                        {
                            MunicipalityId = 112,
                            MunicipalityName = "Kävlinge kommun"
                        },
                        new
                        {
                            MunicipalityId = 113,
                            MunicipalityName = "Köpings kommun"
                        },
                        new
                        {
                            MunicipalityId = 114,
                            MunicipalityName = "Laholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 115,
                            MunicipalityName = "Landskrona kommun"
                        },
                        new
                        {
                            MunicipalityId = 116,
                            MunicipalityName = "Laxå kommun"
                        },
                        new
                        {
                            MunicipalityId = 117,
                            MunicipalityName = "Lekebergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 118,
                            MunicipalityName = "Leksands kommun"
                        },
                        new
                        {
                            MunicipalityId = 119,
                            MunicipalityName = "Lerums kommun"
                        },
                        new
                        {
                            MunicipalityId = 120,
                            MunicipalityName = "Lessebo kommun"
                        },
                        new
                        {
                            MunicipalityId = 121,
                            MunicipalityName = "Lidingö kommun"
                        },
                        new
                        {
                            MunicipalityId = 122,
                            MunicipalityName = "Lidköpings kommun"
                        },
                        new
                        {
                            MunicipalityId = 123,
                            MunicipalityName = "Lilla Edets kommun"
                        },
                        new
                        {
                            MunicipalityId = 124,
                            MunicipalityName = "Lindesbergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 125,
                            MunicipalityName = "Linköpings kommun"
                        },
                        new
                        {
                            MunicipalityId = 126,
                            MunicipalityName = "Ljungby kommun"
                        },
                        new
                        {
                            MunicipalityId = 127,
                            MunicipalityName = "Ljusdals kommun"
                        },
                        new
                        {
                            MunicipalityId = 128,
                            MunicipalityName = "Ljusnarsbergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 129,
                            MunicipalityName = "Lomma kommun"
                        },
                        new
                        {
                            MunicipalityId = 130,
                            MunicipalityName = "Ludvika kommun"
                        },
                        new
                        {
                            MunicipalityId = 131,
                            MunicipalityName = "Luleå kommun"
                        },
                        new
                        {
                            MunicipalityId = 132,
                            MunicipalityName = "Lunds kommun"
                        },
                        new
                        {
                            MunicipalityId = 133,
                            MunicipalityName = "Lycksele kommun"
                        },
                        new
                        {
                            MunicipalityId = 134,
                            MunicipalityName = "Lysekils kommun"
                        },
                        new
                        {
                            MunicipalityId = 135,
                            MunicipalityName = "Malmö kommun"
                        },
                        new
                        {
                            MunicipalityId = 136,
                            MunicipalityName = "Malung-Sälens kommun"
                        },
                        new
                        {
                            MunicipalityId = 137,
                            MunicipalityName = "Malå kommun"
                        },
                        new
                        {
                            MunicipalityId = 138,
                            MunicipalityName = "Mariestads kommun"
                        },
                        new
                        {
                            MunicipalityId = 139,
                            MunicipalityName = "Markaryds kommun"
                        },
                        new
                        {
                            MunicipalityId = 140,
                            MunicipalityName = "Marks kommun"
                        },
                        new
                        {
                            MunicipalityId = 141,
                            MunicipalityName = "Melleruds kommun"
                        },
                        new
                        {
                            MunicipalityId = 142,
                            MunicipalityName = "Mjölby kommun"
                        },
                        new
                        {
                            MunicipalityId = 143,
                            MunicipalityName = "Mora kommun"
                        },
                        new
                        {
                            MunicipalityId = 144,
                            MunicipalityName = "Motala kommun"
                        },
                        new
                        {
                            MunicipalityId = 145,
                            MunicipalityName = "Mullsjö kommun"
                        },
                        new
                        {
                            MunicipalityId = 146,
                            MunicipalityName = "Munkedals kommun"
                        },
                        new
                        {
                            MunicipalityId = 147,
                            MunicipalityName = "Munkfors kommun"
                        },
                        new
                        {
                            MunicipalityId = 148,
                            MunicipalityName = "Mölndals kommun"
                        },
                        new
                        {
                            MunicipalityId = 149,
                            MunicipalityName = "Mönsterås kommun"
                        },
                        new
                        {
                            MunicipalityId = 150,
                            MunicipalityName = "Mörbylånga kommun"
                        },
                        new
                        {
                            MunicipalityId = 151,
                            MunicipalityName = "Nacka kommun"
                        },
                        new
                        {
                            MunicipalityId = 152,
                            MunicipalityName = "Nora kommun"
                        },
                        new
                        {
                            MunicipalityId = 153,
                            MunicipalityName = "Norbergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 154,
                            MunicipalityName = "Nordanstigs kommun"
                        },
                        new
                        {
                            MunicipalityId = 155,
                            MunicipalityName = "Nordmalings kommun"
                        },
                        new
                        {
                            MunicipalityId = 156,
                            MunicipalityName = "Norrköpings kommun"
                        },
                        new
                        {
                            MunicipalityId = 157,
                            MunicipalityName = "Norrtälje kommun"
                        },
                        new
                        {
                            MunicipalityId = 158,
                            MunicipalityName = "Norsjö kommun"
                        },
                        new
                        {
                            MunicipalityId = 159,
                            MunicipalityName = "Nybro kommun"
                        },
                        new
                        {
                            MunicipalityId = 160,
                            MunicipalityName = "Nykvarns kommun"
                        },
                        new
                        {
                            MunicipalityId = 161,
                            MunicipalityName = "Nyköpings kommun"
                        },
                        new
                        {
                            MunicipalityId = 162,
                            MunicipalityName = "Nynäshamns kommun"
                        },
                        new
                        {
                            MunicipalityId = 163,
                            MunicipalityName = "Nässjö kommun"
                        },
                        new
                        {
                            MunicipalityId = 164,
                            MunicipalityName = "Ockelbo kommun"
                        },
                        new
                        {
                            MunicipalityId = 165,
                            MunicipalityName = "Olofströms kommun"
                        },
                        new
                        {
                            MunicipalityId = 166,
                            MunicipalityName = "Orsa kommun"
                        },
                        new
                        {
                            MunicipalityId = 167,
                            MunicipalityName = "Orust kommun"
                        },
                        new
                        {
                            MunicipalityId = 168,
                            MunicipalityName = "Osby kommun"
                        },
                        new
                        {
                            MunicipalityId = 169,
                            MunicipalityName = "Oskarshamns kommun"
                        },
                        new
                        {
                            MunicipalityId = 170,
                            MunicipalityName = "Ovanåkers kommun"
                        },
                        new
                        {
                            MunicipalityId = 171,
                            MunicipalityName = "Oxelösunds kommun"
                        },
                        new
                        {
                            MunicipalityId = 172,
                            MunicipalityName = "Pajala kommun"
                        },
                        new
                        {
                            MunicipalityId = 173,
                            MunicipalityName = "Partille kommun"
                        },
                        new
                        {
                            MunicipalityId = 174,
                            MunicipalityName = "Perstorps kommun"
                        },
                        new
                        {
                            MunicipalityId = 175,
                            MunicipalityName = "Piteå kommun"
                        },
                        new
                        {
                            MunicipalityId = 176,
                            MunicipalityName = "Ragunda kommun"
                        },
                        new
                        {
                            MunicipalityId = 177,
                            MunicipalityName = "Robertsfors kommun"
                        },
                        new
                        {
                            MunicipalityId = 178,
                            MunicipalityName = "Ronneby kommun"
                        },
                        new
                        {
                            MunicipalityId = 179,
                            MunicipalityName = "Rättviks kommun"
                        },
                        new
                        {
                            MunicipalityId = 180,
                            MunicipalityName = "Sala kommun"
                        },
                        new
                        {
                            MunicipalityId = 181,
                            MunicipalityName = "Salems kommun"
                        },
                        new
                        {
                            MunicipalityId = 182,
                            MunicipalityName = "Sandvikens kommun"
                        },
                        new
                        {
                            MunicipalityId = 183,
                            MunicipalityName = "Sigtuna kommun"
                        },
                        new
                        {
                            MunicipalityId = 184,
                            MunicipalityName = "Simrishamns kommun"
                        },
                        new
                        {
                            MunicipalityId = 185,
                            MunicipalityName = "Sjöbo kommun"
                        },
                        new
                        {
                            MunicipalityId = 186,
                            MunicipalityName = "Skara kommun"
                        },
                        new
                        {
                            MunicipalityId = 187,
                            MunicipalityName = "Skellefteå kommun"
                        },
                        new
                        {
                            MunicipalityId = 188,
                            MunicipalityName = "Skinnskattebergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 189,
                            MunicipalityName = "Skurups kommun"
                        },
                        new
                        {
                            MunicipalityId = 190,
                            MunicipalityName = "Skövde kommun"
                        },
                        new
                        {
                            MunicipalityId = 191,
                            MunicipalityName = "Smedjebackens kommun"
                        },
                        new
                        {
                            MunicipalityId = 192,
                            MunicipalityName = "Sollefteå kommun"
                        },
                        new
                        {
                            MunicipalityId = 193,
                            MunicipalityName = "Sollentuna kommun"
                        },
                        new
                        {
                            MunicipalityId = 194,
                            MunicipalityName = "Solna kommun"
                        },
                        new
                        {
                            MunicipalityId = 195,
                            MunicipalityName = "Sorsele kommun"
                        },
                        new
                        {
                            MunicipalityId = 196,
                            MunicipalityName = "Sotenäs kommun"
                        },
                        new
                        {
                            MunicipalityId = 197,
                            MunicipalityName = "Staffanstorps kommun"
                        },
                        new
                        {
                            MunicipalityId = 198,
                            MunicipalityName = "Stenungsunds kommun"
                        },
                        new
                        {
                            MunicipalityId = 199,
                            MunicipalityName = "Stockholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 200,
                            MunicipalityName = "Storfors kommun"
                        },
                        new
                        {
                            MunicipalityId = 201,
                            MunicipalityName = "Storumans kommun"
                        },
                        new
                        {
                            MunicipalityId = 202,
                            MunicipalityName = "Strängnäs kommun"
                        },
                        new
                        {
                            MunicipalityId = 203,
                            MunicipalityName = "Strömstads kommun"
                        },
                        new
                        {
                            MunicipalityId = 204,
                            MunicipalityName = "Strömsunds kommun"
                        },
                        new
                        {
                            MunicipalityId = 205,
                            MunicipalityName = "Sundbybergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 206,
                            MunicipalityName = "Sundsvalls kommun"
                        },
                        new
                        {
                            MunicipalityId = 207,
                            MunicipalityName = "Sunne kommun"
                        },
                        new
                        {
                            MunicipalityId = 208,
                            MunicipalityName = "Surahammars kommun"
                        },
                        new
                        {
                            MunicipalityId = 209,
                            MunicipalityName = "Svalövs kommun"
                        },
                        new
                        {
                            MunicipalityId = 210,
                            MunicipalityName = "Svedala kommun"
                        },
                        new
                        {
                            MunicipalityId = 211,
                            MunicipalityName = "Svenljunga kommun"
                        },
                        new
                        {
                            MunicipalityId = 212,
                            MunicipalityName = "Säffle kommun"
                        },
                        new
                        {
                            MunicipalityId = 213,
                            MunicipalityName = "Säters kommun"
                        },
                        new
                        {
                            MunicipalityId = 214,
                            MunicipalityName = "Sävsjö kommun"
                        },
                        new
                        {
                            MunicipalityId = 215,
                            MunicipalityName = "Söderhamns kommun"
                        },
                        new
                        {
                            MunicipalityId = 216,
                            MunicipalityName = "Söderköpings kommun"
                        },
                        new
                        {
                            MunicipalityId = 217,
                            MunicipalityName = "Södertälje kommun"
                        },
                        new
                        {
                            MunicipalityId = 218,
                            MunicipalityName = "Sölvesborgs kommun"
                        },
                        new
                        {
                            MunicipalityId = 219,
                            MunicipalityName = "Tanums kommun"
                        },
                        new
                        {
                            MunicipalityId = 220,
                            MunicipalityName = "Tibro kommun"
                        },
                        new
                        {
                            MunicipalityId = 221,
                            MunicipalityName = "Tidaholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 222,
                            MunicipalityName = "Tierps kommun"
                        },
                        new
                        {
                            MunicipalityId = 223,
                            MunicipalityName = "Timrå kommun"
                        },
                        new
                        {
                            MunicipalityId = 224,
                            MunicipalityName = "Tingsryds kommun"
                        },
                        new
                        {
                            MunicipalityId = 225,
                            MunicipalityName = "Tjörns kommun"
                        },
                        new
                        {
                            MunicipalityId = 226,
                            MunicipalityName = "Tomelilla kommun"
                        },
                        new
                        {
                            MunicipalityId = 227,
                            MunicipalityName = "Torsby kommun"
                        },
                        new
                        {
                            MunicipalityId = 228,
                            MunicipalityName = "Torsås kommun"
                        },
                        new
                        {
                            MunicipalityId = 229,
                            MunicipalityName = "Tranemo kommun"
                        },
                        new
                        {
                            MunicipalityId = 230,
                            MunicipalityName = "Tranås kommun"
                        },
                        new
                        {
                            MunicipalityId = 231,
                            MunicipalityName = "Trelleborgs kommun"
                        },
                        new
                        {
                            MunicipalityId = 232,
                            MunicipalityName = "Trollhättans kommun"
                        },
                        new
                        {
                            MunicipalityId = 233,
                            MunicipalityName = "Trosa kommun"
                        },
                        new
                        {
                            MunicipalityId = 234,
                            MunicipalityName = "Tyresö kommun"
                        },
                        new
                        {
                            MunicipalityId = 235,
                            MunicipalityName = "Täby kommun"
                        },
                        new
                        {
                            MunicipalityId = 236,
                            MunicipalityName = "Töreboda kommun"
                        },
                        new
                        {
                            MunicipalityId = 237,
                            MunicipalityName = "Uddevalla kommun"
                        },
                        new
                        {
                            MunicipalityId = 238,
                            MunicipalityName = "Ulricehamns kommun"
                        },
                        new
                        {
                            MunicipalityId = 239,
                            MunicipalityName = "Umeå kommun"
                        },
                        new
                        {
                            MunicipalityId = 240,
                            MunicipalityName = "Upplands Väsby kommun"
                        },
                        new
                        {
                            MunicipalityId = 241,
                            MunicipalityName = "Upplands-Bro kommun"
                        },
                        new
                        {
                            MunicipalityId = 242,
                            MunicipalityName = "Uppsala kommun"
                        },
                        new
                        {
                            MunicipalityId = 243,
                            MunicipalityName = "Uppvidinge kommun"
                        },
                        new
                        {
                            MunicipalityId = 244,
                            MunicipalityName = "Vadstena kommun"
                        },
                        new
                        {
                            MunicipalityId = 245,
                            MunicipalityName = "Vaggeryds kommun"
                        },
                        new
                        {
                            MunicipalityId = 246,
                            MunicipalityName = "Valdemarsviks kommun"
                        },
                        new
                        {
                            MunicipalityId = 247,
                            MunicipalityName = "Vallentuna kommun"
                        },
                        new
                        {
                            MunicipalityId = 248,
                            MunicipalityName = "Vansbro kommun"
                        },
                        new
                        {
                            MunicipalityId = 249,
                            MunicipalityName = "Vara kommun"
                        },
                        new
                        {
                            MunicipalityId = 250,
                            MunicipalityName = "Varbergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 251,
                            MunicipalityName = "Vaxholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 252,
                            MunicipalityName = "Vellinge kommun"
                        },
                        new
                        {
                            MunicipalityId = 253,
                            MunicipalityName = "Vetlanda kommun"
                        },
                        new
                        {
                            MunicipalityId = 254,
                            MunicipalityName = "Vilhelmina kommun"
                        },
                        new
                        {
                            MunicipalityId = 255,
                            MunicipalityName = "Vimmerby kommun"
                        },
                        new
                        {
                            MunicipalityId = 256,
                            MunicipalityName = "Vindelns kommun"
                        },
                        new
                        {
                            MunicipalityId = 257,
                            MunicipalityName = "Vingåkers kommun"
                        },
                        new
                        {
                            MunicipalityId = 258,
                            MunicipalityName = "Vårgårda kommun"
                        },
                        new
                        {
                            MunicipalityId = 259,
                            MunicipalityName = "Vänersborgs kommun"
                        },
                        new
                        {
                            MunicipalityId = 260,
                            MunicipalityName = "Vännäs kommun"
                        },
                        new
                        {
                            MunicipalityId = 261,
                            MunicipalityName = "Värmdö kommun"
                        },
                        new
                        {
                            MunicipalityId = 262,
                            MunicipalityName = "Värnamo kommun"
                        },
                        new
                        {
                            MunicipalityId = 263,
                            MunicipalityName = "Västerviks kommun"
                        },
                        new
                        {
                            MunicipalityId = 264,
                            MunicipalityName = "Västerås kommun"
                        },
                        new
                        {
                            MunicipalityId = 265,
                            MunicipalityName = "Växjö kommun"
                        },
                        new
                        {
                            MunicipalityId = 266,
                            MunicipalityName = "Ydre kommun"
                        },
                        new
                        {
                            MunicipalityId = 267,
                            MunicipalityName = "Ystads kommun"
                        },
                        new
                        {
                            MunicipalityId = 268,
                            MunicipalityName = "Åmåls kommun"
                        },
                        new
                        {
                            MunicipalityId = 269,
                            MunicipalityName = "Ånge kommun"
                        },
                        new
                        {
                            MunicipalityId = 270,
                            MunicipalityName = "Åre kommun"
                        },
                        new
                        {
                            MunicipalityId = 271,
                            MunicipalityName = "Årjängs kommun"
                        },
                        new
                        {
                            MunicipalityId = 272,
                            MunicipalityName = "Åsele kommun"
                        },
                        new
                        {
                            MunicipalityId = 273,
                            MunicipalityName = "Åstorps kommun"
                        },
                        new
                        {
                            MunicipalityId = 274,
                            MunicipalityName = "Åtvidabergs kommun"
                        },
                        new
                        {
                            MunicipalityId = 275,
                            MunicipalityName = "Älmhults kommun"
                        },
                        new
                        {
                            MunicipalityId = 276,
                            MunicipalityName = "Älvdalens kommun"
                        },
                        new
                        {
                            MunicipalityId = 277,
                            MunicipalityName = "Älvkarleby kommun"
                        },
                        new
                        {
                            MunicipalityId = 278,
                            MunicipalityName = "Älvsbyns kommun"
                        },
                        new
                        {
                            MunicipalityId = 279,
                            MunicipalityName = "Ängelholms kommun"
                        },
                        new
                        {
                            MunicipalityId = 280,
                            MunicipalityName = "Öckerö kommun"
                        },
                        new
                        {
                            MunicipalityId = 281,
                            MunicipalityName = "Ödeshögs kommun"
                        },
                        new
                        {
                            MunicipalityId = 282,
                            MunicipalityName = "Örebro kommun"
                        },
                        new
                        {
                            MunicipalityId = 283,
                            MunicipalityName = "Örkelljunga kommun"
                        },
                        new
                        {
                            MunicipalityId = 284,
                            MunicipalityName = "Örnsköldsviks kommun"
                        },
                        new
                        {
                            MunicipalityId = 285,
                            MunicipalityName = "Östersunds kommun"
                        },
                        new
                        {
                            MunicipalityId = 286,
                            MunicipalityName = "Österåkers kommun"
                        },
                        new
                        {
                            MunicipalityId = 287,
                            MunicipalityName = "Östhammars kommun"
                        },
                        new
                        {
                            MunicipalityId = 288,
                            MunicipalityName = "Östra Göinge kommun"
                        },
                        new
                        {
                            MunicipalityId = 289,
                            MunicipalityName = "Överkalix kommun"
                        },
                        new
                        {
                            MunicipalityId = 290,
                            MunicipalityName = "Övertorneå kommun"
                        });
                });

            modelBuilder.Entity("FribergFastigheter.Data.Entities.Housing", b =>
                {
                    b.HasOne("FribergFastigheterApi.Data.Entities.BrokerFirm", "BrokerFirm")
                        .WithMany()
                        .HasForeignKey("BrokerFirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FribergFastigheterApi.Data.Entities.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FribergFastigheterApi.Data.Entities.HousingCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryHousingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FribergFastigheterApi.Data.Entities.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");

                    b.Navigation("BrokerFirm");

                    b.Navigation("Category");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("FribergFastigheterApi.Data.Entities.Broker", b =>
                {
                    b.HasOne("FribergFastigheterApi.Data.Entities.BrokerFirm", "BrokerFirm")
                        .WithMany("Brokers")
                        .HasForeignKey("BrokerFirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrokerFirm");
                });

            modelBuilder.Entity("FribergFastigheterApi.Data.Entities.Image", b =>
                {
                    b.HasOne("FribergFastigheter.Data.Entities.Housing", null)
                        .WithMany("Images")
                        .HasForeignKey("HousingId");
                });

            modelBuilder.Entity("FribergFastigheter.Data.Entities.Housing", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("FribergFastigheterApi.Data.Entities.BrokerFirm", b =>
                {
                    b.Navigation("Brokers");
                });
#pragma warning restore 612, 618
        }
    }
}
